name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test_gcc:
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-gcc

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up cargo
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
      env:
        HOME: /root

    - name: Build SSVM-napi using gcc
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        JOBS=max npm install --fallback-to-build --update-binary . --unsafe-perm
      env:
        HOME: /root

  build_test_clang:
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-clang

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up cargo
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
      env:
        HOME: /root

    - name: Build SSVM-napi using clang
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        JOBS=max npm install --fallback-to-build --update-binary . --unsafe-perm
      env:
        HOME: /root
