name: External Test

on:
  push:
    branches:
    - master
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - master


jobs:
  test_wasm_learning:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu2004_x86_64

    strategy:
      matrix:
        wasmedge-options: ['', '--enable-aot']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout wasm-learning
      uses: actions/checkout@v2
      with:
        repository: second-state/wasm-learning
        path: wasm-learning
        ref: wasmedge-test

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set Rust to required version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.50.0
        override: true

    - name: Install dependencies
      run: |
        apt update && apt install -y libclang-dev sudo
        npm install -g --unsafe-perm rustwasmc

    - name: Build and install wasmedge-extensions
      uses: './wasmedge-core/.github/actions/build-from-source'

    - name: Test functions ${{ matrix.wasmedge-options }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/functions

    - name: Test JSON IO ${{ matrix.wasmedge-options }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/json_io

    - name: Test WASI ${{ matrix.wasmedge-options }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/wasi

    - name: Test KMeans ${{ matrix.wasmedge-options }}
      if: ${{ contains(matrix.wasmedge-options, 'aot') }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        cd node && node app.js && cd ..
        rustwasmc clean
      working-directory: wasm-learning/nodejs/kmeans

    - name: Test MobileNet ${{ matrix.wasmedge-options }}
      if: ${{ contains(matrix.wasmedge-options, 'aot') }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        cd test && node test.js && cd ..
        rustwasmc clean
      working-directory: wasm-learning/faas/mobilenet

    - name: Test MTCNN ${{ matrix.wasmedge-options }}
      if: ${{ contains(matrix.wasmedge-options, 'aot') }}
      run: |
        rustwasmc build ${{ matrix.wasmedge-options }} --enable-ext
        cd pkg && npm i ${GITHUB_WORKSPACE} && cd ..
        cd test && node test.js && cd ..
        rustwasmc clean
      working-directory: wasm-learning/faas/mtcnn
