name: Main Workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu2004_x86_64

    strategy:
      matrix:
        include:
        - cc: 'clang'
          cxx: 'clang++'
        - cc: 'gcc'
          cxx: 'g++'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set Rust to required version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.50.0
        override: true

    - name: Install dependencies
      run: |
        apt update && apt install -y libclang-dev sudo
        npm install -g --unsafe-perm rustwasmc

    - name: Install clang if needed
      if: ${{ contains(matrix.cc, 'clang') }}
      run: |
        apt update && apt install -y clang

    - name: Build wasmedge-core with ${{ matrix.cc }}
      uses: './wasmedge-core/.github/actions/build-from-source'
      with:
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}
